disabled_rules:
- trailing_whitespace
- nesting

excluded:
- InteractionSample/R.generated.swift
- InteractionSampleTests/
- InteractionSampleUITests/
- Pods/
- Podfile
- Podfile.lock

line_length: 300

variable_name:
    max_length:
        warning: 60
        error: 80
    min_length:
        warning: 1
        error: 0
